version: "3.8"
services:
  frontend:
    build:
      context: ./OpenCalendar-Frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - OpenCalendar-Backend

  backend:
    build:
      context: ./OpenCalendar-Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
