version: "3.8"

services:
  backend:
    build:
      context: ./OpenCalendar-Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_WEB_RESOURCES_STATIC_LOCATIONS: "classpath:/static/"
    depends_on:
      - frontend

  frontend:
    build:
      context: ./OpenCalendar-Frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      VITE_API_URL: "http://localhost:8080"
