version: "3.8"

# ───────────────────────── Services ─────────────────────────
services:
  # Backend
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: production
      SPRING_CACHE_HOST: redis
      SPRING_CACHE_PORT: 6379
    volumes:
      - ./Backend/database:/app/database
    depends_on:
      - redis
    networks:
      - opencalendar-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  # Frontend
  frontend:
    build:
      context: ./OpenCalendar-Frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      VITE_API_URL: https://open-calendar-backend.onrender.com:8080
    networks:
      - opencalendar-network
    restart: unless-stopped

  # Database
  database:
  image: postgres:16
  container_name: open-calendar-database
  restart: unless-stopped
  environment:
    POSTGRES_DB: open_calendar_database
    POSTGRES_USER: admin
    POSTGRES_PASSWORD: password
  volumes:
    - postgres_data:/var/lib/postgresql/data
  networks:
    - opencalendar-network
  healthcheck:
    test: ["CMD-SHELL", "pg_isready -U admin"]
    interval: 30s
    timeout: 5s
    retries: 5

  # Redis
  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    command:
      - redis-server
      - "--save"
      - "60"
      - "1"
      - "--loglevel"
      - "warning"
    networks:
      - opencalendar-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

# ───────────────────────── Networks ─────────────────────────
networks:
  opencalendar-network:
    driver: bridge
