version: "3.8"

# ───────────────────────── Services ─────────────────────────
services:
  # Redis
  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    command:
      - redis-server
      - "--save"
      - "60"
      - "1"
      - "--loglevel"
      - "warning"
    networks:
      - opencalendar-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Backend
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: production
      SPRING_CACHE_HOST: redis
      SPRING_CACHE_PORT: 6379
    volumes:
      - ./Backend/database:/app/database
    depends_on:
      - redis
    networks:
      - opencalendar-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  # Frontend
  frontend:
    build:
      context: ./OpenCalendar-Frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      VITE_MODE: microservices
      VITE_BACKEND_URL: http://backend:8080
      VITE_CC_URL: http://cc-service:8080
      VITE_TEN_URL: http://ten-service:8080
    networks:
      - opencalendar-network
    restart: unless-stopped

# ───────────────────────── Networks ─────────────────────────
networks:
  opencalendar-network:
    driver: bridge
