version: "3.8"

services:
  backend:
    build:
      context: ./OpenCalendar-Backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      SPRING_WEB_RESOURCES_STATIC_LOCATIONS: "classpath:/static/"

  frontend:
    build:
      context: ./OpenCalendar-Frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    environment:
      VITE_API_URL: "http://backend:8080"
    depends_on:
      - backend
