version: "3.8"

# ───────────────────────── Services ─────────────────────────
services:
  # Backend
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: production
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-d16802uuk2gs73clf2hg-a:5432/open_calendar_database
      SPRING_DATASOURCE_USERNAME: open_calendar_database_user
      SPRING_CACHE_HOST: redis
      SPRING_CACHE_PORT: 6379
    depends_on:
      - redis
    networks:
      - opencalendar-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

  # Frontend
  frontend:
    build:
      context: ./OpenCalendar-Frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      VITE_API_URL: http://backend:8080
    networks:
      - opencalendar-network
    restart: unless-stopped

  # Redis
  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    command:
      - redis-server
      - "--save"
      - "60"
      - "1"
      - "--loglevel"
      - "warning"
    networks:
      - opencalendar-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

# ───────────────────────── Networks ─────────────────────────
networks:
  opencalendar-network:
    driver: bridge
