version: "1"
services:
  - type: redis
    name: open-calendar-redis
    plan: free
    ipAllowList:
      - 100.20.92.101
      - 44.225.181.72
      - 44.227.217.144

  - type: web
    name: open-calendar-backend
    runtime: docker
    repo: https://github.com/0zzz7y/OpenCalendar-Backend
    branch: main
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SPRING_CACHE_HOST
        fromService:
          name: open-calendar-redis
          type: redis
          property: host
      - key: SPRING_CACHE_PORT
        fromService:
          name: open-calendar-redis
          type: redis
          property: port
      - key: SPRING_WEB_RESOURCES_STATIC_LOCATIONS
        value: classpath:/static/

  - type: web
    name: open-calendar-cc-service
    runtime: docker
    repo: https://github.com/0zzz7y/OpenCalendar-Cc
    branch: main
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SERVER_PORT
        value: "8081"
      - key: SPRING_CACHE_HOST
        fromService:
          name: open-calendar-redis
          type: redis
          property: host
      - key: SPRING_CACHE_PORT
        fromService:
          name: open-calendar-redis
          type: redis
          property: port

  - type: web
    name: open-calendar-ten-service
    runtime: docker
    repo: https://github.com/0zzz7y/OpenCalendar-Event
    branch: main
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SERVER_PORT
        value: "8082"
      - key: SPRING_CACHE_HOST
        fromService:
          name: open-calendar-redis
          type: redis
          property: host
      - key: SPRING_CACHE_PORT
        fromService:
          name: open-calendar-redis
          type: redis
          property: port

  - type: web
    name: open-calendar-frontend
    runtime: docker
    repo: https://github.com/0zzz7y/OpenCalendar-Frontend
    branch: main
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: VITE_BACKEND_URL
        value: https://open-calendar-backend.onrender.com
      - key: VITE_CC_URL
        value: https://open-calendar-cc-service.onrender.com
      - key: VITE_TEN_URL
        value: https://open-calendar-ten-service.onrender.com
