version: "1"

# ───────────────────────── Services ─────────────────────────
services:
  # Backend
  - type: web
    name: open-calendar-backend
    repo: https://github.com/0zzz7y/OpenCalendar-Backend
    branch: main
    runtime: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SPRING_WEB_RESOURCES_STATIC_LOCATIONS
        value: classpath:/static/
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d16802uuk2gs73clf2hg-a.oregon-postgres.render.com/open_calendar_database
      - key: SPRING_DATASOURCE_USERNAME
        value: open_calendar_database_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: ${POSTGRES_PASSWORD}
      - key: SPRING_CACHE_HOST
        fromService:
          name: open-calendar-redis
          type: redis
          property: host
      - key: SPRING_CACHE_PORT
        fromService:
          name: open-calendar-redis
          type: redis
          property: port

  # Frontend
  - type: web
    name: open-calendar-frontend
    repo: https://github.com/0zzz7y/OpenCalendar-Frontend
    branch: main
    runtime: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: VITE_API_URL
        value: https://open-calendar-backend.onrender.com

  # Redis
  - type: redis
    name: open-calendar-redis
    plan: free
    ipAllowList:
      - source: 100.20.92.101
      - source: 44.225.181.72
      - source: 44.227.217.144

# ───────────────────────── Databases ─────────────────────────
databases:
  - name: open-calendar-database
    databaseName: open_calendar_database
    user: open_calendar_database_user
    plan: free
    ipAllowList:
      - source: 100.20.92.101
        description: production-1
      - source: 44.225.181.72
        description: production-2
      - source: 44.227.217.144
        description: production-3
