services:
  - type: web
    name: open-calendar-frontend
    runtime: docker
    repo: https://github.com/0zzz7y/OpenCalendar-Frontend
    branch: main
    rootDir: OpenCalendar-Frontend
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: VITE_API_URL
        value: http://open-calendar-backend:8080

  - type: web
    name: open-calendar-backend
    runtime: docker
    repo: https://github.com/0zzz7y/OpenCalendar-Backend
    branch: main
    rootDir: OpenCalendar-Backend
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: SPRING_WEB_RESOURCES_STATIC_LOCATIONS
        value: classpath:/static/
